### PR TITLE
feat: use slim image, use volumes

### PR DESCRIPTION
**Pull request by ewrogers**
I've been working on a similar Docker server setup for Longvinter and decided to fork the "official" repo and add my changes with some rationale:

1. Use `debian:buster-slim` base image, allows a smaller image size.
2. Extract the steam user, ID, and home to `ENV` vars
3. Use mounted volume for persisting `/data` directory
4. Install Steam SDK into `/home/steam/steamcmd` for simplicity
5. Use `ln -s` for `sdk64` instead of copying binaries
6. Expose port `27015` as well
7. Re-arrange Dockerfile to reduce unnecessary rebuilds
8. Rename `app` user to `steam` for convention (see `cm2network/steamcmd` base image)
9. Change restart behavior to `unless-stopped` to avoid looping behavior

The main thing #3 (using volumes) instead of a `/data` directory with awkward local filesystem settings having to chmod with an arbitrary UID.

Also, separating `/home/steam` from the `/data` directory allows persistent data to be stored in a volume where the SteamCMD/SDK binaries remain in the container image itself.

### CODE REVIEW

**Comment by tvandoorn** [comment]
Hi, thanks for improving the Docker setup! I have tested the changes you made and it all seems to work as expected. I would like to touch on changes 3 and 6 however.

Change 3
I agree that using volumes makes it easier in terms of setup. However, using volumes makes things more complicated for less-experienced users in regards to things like backups, modding and troubleshooting. They might not know how to copy data from or to the volume. This is the reason I chose to use a data directory instead of a volume. If you could make the following changes to the readme I think this should not be a problem:
- Rename chapter "Creating the data directory" to "Setting up a data directory"
- Add reasons to use a data directory instead of a volume (easy file access for things like backups, modding, etc.)
- Add yaml snippet users can copy-paste to change to use the data directory instead
- Add note to chapter "Running multiple Longvinter containers on one Docker server" that explains that the volume name has to be changed when running multiple servers (also provide example yaml snippet).

Change 6
I would like to suggest removing the expose on port 27015 from both the `Dockerfile` and `docker-compose.yaml` for these reasons. From my testing port 27015 does not appear to serve any purpose, and the server works as expected with ports 7777 and 27016 (or any other port if the user changes it), even when running multiple servers at once. It also does not appear to have a parameter to change it when running the server, so I purposely left it out as it may cause confusion with users.

Again, thanks for improving the Docker setup. The changes you made are very useful and much appreciated. If you could implement the changes I proposed I'll be sure to merge the changes into this repository.

**Comment by ewrogers** [comment]
Absolutely! Will make those changes tomorrow, appreciate the feedback and quick reply.

I know volumes introduce a level of complexity and management that may not be familiar to some, but I would argue that anyone who runs the Linux server instead of the Windows variant, and is comfortable with Docker should be experienced enough to handle `docker volume inspect` and getting to the actual volume store.

I was curious about port `27015` myself and the only reason I added it was that the official server guide mentions needing it. But if it functions without, I'm all for removing it (the less ports exposed the better).

As for the backup situation, I'm still trying to figure out how/when the game server saves. In my early testing I was stopping the container and restarting it, noticing that data would sometimes not persist. I wasn't sure if there is some interval that it saves or if it guarantees all current player data to be saved on stop. I tested it today and it seemed to work as expected but there was also a patch so if you know any details on that I'd love to know!

**Comment by ewrogers** [comment]
@tvandoorn I've updated the README with those things and removed the port `27015` from the container and `docker-compose.yaml` file. I've also added some constraints to the logging so it doesn't eat up the entire disk over time.

**Comment by tvandoorn** [comment]
Hi! Sorry for the late reply, couldn't get around to checking your changes earlier unfortunately. Your changes look good so I have merged the pull request. Thanks again for improving the Docker setup!

**Pull request merged**
